<?php
/**
 * InlineResponse2005ItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REMESITA API REST
 *
 * Api de remesita.com para desarrolladores. Primero obten tu apiKey y apiSecret, y para autenticarte debes ejecutar el endpoint rest/v1/auth en la respuesta obtendrás un token de acceso que debes usar en el resto de peticiones
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse2005ItemsTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2005Items
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2005ItemsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2005Items"
     */
    public function testInlineResponse2005Items()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "speed_mode"
     */
    public function testPropertySpeedMode()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "recipient_account"
     */
    public function testPropertyRecipientAccount()
    {
    }

    /**
     * Test attribute "swift"
     */
    public function testPropertySwift()
    {
    }

    /**
     * Test attribute "institution"
     */
    public function testPropertyInstitution()
    {
    }

    /**
     * Test attribute "sender_name"
     */
    public function testPropertySenderName()
    {
    }

    /**
     * Test attribute "sender_country"
     */
    public function testPropertySenderCountry()
    {
    }

    /**
     * Test attribute "recipient_name"
     */
    public function testPropertyRecipientName()
    {
    }

    /**
     * Test attribute "recipient_country"
     */
    public function testPropertyRecipientCountry()
    {
    }

    /**
     * Test attribute "recipient_relationship"
     */
    public function testPropertyRecipientRelationship()
    {
    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "quotation"
     */
    public function testPropertyQuotation()
    {
    }

    /**
     * Test attribute "sender_currency"
     */
    public function testPropertySenderCurrency()
    {
    }

    /**
     * Test attribute "exchange_rate"
     */
    public function testPropertyExchangeRate()
    {
    }

    /**
     * Test attribute "life_time"
     */
    public function testPropertyLifeTime()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "payed_at"
     */
    public function testPropertyPayedAt()
    {
    }

    /**
     * Test attribute "cancel_at"
     */
    public function testPropertyCancelAt()
    {
    }

    /**
     * Test attribute "completed_at"
     */
    public function testPropertyCompletedAt()
    {
    }

    /**
     * Test attribute "institution_icon"
     */
    public function testPropertyInstitutionIcon()
    {
    }

    /**
     * Test attribute "cancel_reason"
     */
    public function testPropertyCancelReason()
    {
    }

    /**
     * Test attribute "intent"
     */
    public function testPropertyIntent()
    {
    }
}
