<?php
/**
 * PrepaidCardsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REMESITA API REST
 *
 * Api de remesita.com para desarrolladores. Primero obten tu apiKey y apiSecret, y para autenticarte debes ejecutar el endpoint rest/v1/auth en la respuesta obtendrás un token de acceso que debes usar en el resto de peticiones
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PrepaidCardsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PrepaidCardsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for restV1CardNumberTogglePost
     *
     * Bloquea o desbloquea una tarjeta.
     *
     */
    public function testRestV1CardNumberTogglePost()
    {
    }

    /**
     * Test case for restV1CardNumberTransactionsPgPgSizeGet
     *
     * Obtiene las transacciones de una tarjeta.
     *
     */
    public function testRestV1CardNumberTransactionsPgPgSizeGet()
    {
    }

    /**
     * Test case for restV1CardTransferBetweenPost
     *
     * Transfiere saldo entre cuentas Remesita.
     *
     */
    public function testRestV1CardTransferBetweenPost()
    {
    }

    /**
     * Test case for restV1CardsGet
     *
     * Obtiene la lista de tarjetas prepagadas.
     *
     */
    public function testRestV1CardsGet()
    {
    }
}
